Only add apt-transport-https pkg if none exists.
This is needed to work around resource cloning deprecation errors in
Chef 12. I believe this can go away in Chef 13, when resource cloning is
disabled entirely and attempts like this to create new resources with
the same name will just result in unique resources.

    ERROR: Cloning resource attributes for apt_package[apt-transport-https] from prior resource (CHEF-3694)